drop table if exists mpa_default;

CREATE TABLE IF NOT EXISTS mpa_default
(
    mpa_id integer generated by default as identity primary key,
    name   varchar(255)
);

INSERT INTO mpa_default (MPA_ID, NAME)
VALUES (1, 'G'),
       (2, 'PG'),
       (3, 'PG-13'),
       (4, 'R'),
       (5, 'NC-17');

drop table if exists genre_names_default;

CREATE TABLE IF NOT EXISTS genre_names_default
(
    genre_id integer generated by default as identity primary key,
    name     varchar(255)
);

INSERT INTO genre_names_default (GENRE_ID, NAME)
VALUES (1, 'Комедия'),
       (2, 'Драма'),
       (3, 'Мультфильм'),
       (4, 'Триллер'),
       (5, 'Документальный'),
       (6, 'Боевик');

merge into MPA as target using mpa_default as source
on source.mpa_id = target.MPA_ID
when not matched then
    insert (MPA_ID, NAME)
    values (source.mpa_id, source.name);

merge into GENRE_NAMES as target using genre_names_default as source
on source.genre_id = target.GENRE_ID
when not matched then
    insert (GENRE_ID, NAME)
    values (source.genre_id, source.name);