CREATE TABLE IF NOT EXISTS genre_names
(
    genre_id integer generated by default as identity primary key,
    name     varchar(255)
);

CREATE TABLE IF NOT EXISTS mpa
(
    mpa_id integer generated by default as identity primary key,
    name   varchar(255)
);

CREATE TABLE IF NOT EXISTS films
(
    film_id      integer generated by default as identity primary key,
    name         varchar(255),
    description  varchar(255),
    release_date date,
    duration     integer,
    mpa_id       integer references mpa (mpa_id)
);

CREATE TABLE IF NOT EXISTS genres
(
    film_id  integer not null references films (film_id),
    genre_id integer not null references genre_names (genre_id),
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS users
(
    user_id  integer generated by default as identity primary key,
    email    varchar(255),
    login    varchar(255),
    name     varchar(255),
    birthday date
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id   integer     not null references users (user_id),
    friend_id integer     not null references users (user_id),
    status    varchar(10) not null,
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS likes
(
    film_id integer not null references films (film_id),
    user_id integer not null references users (user_id),
    PRIMARY KEY (film_id, user_id)
);